#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Nov 08, 2019 02:30:51 PM CST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 250x180+409+113
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Python NFC R/W"
    vTcl:DefineAlias "$top" "TopLevel" vTcl:Toplevel:WidgetProc "" 1
    entry $top.ent46 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent46" "EntryData" vTcl:WidgetProc "TopLevel" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Hex (Send)} 
    vTcl:DefineAlias "$top.lab47" "LabelData" vTcl:WidgetProc "TopLevel" 1
    button $top.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Read 
    vTcl:DefineAlias "$top.but48" "ButtonRead" vTcl:WidgetProc "TopLevel" 1
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Write 
    vTcl:DefineAlias "$top.but49" "ButtonWrite" vTcl:WidgetProc "TopLevel" 1
    ttk::combobox $top.tCo43 \
        -font TkTextFont -textvariable sectorlist -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo43" "OptionSector" vTcl:WidgetProc "TopLevel" 1
    ttk::combobox $top.tCo44 \
        -font TkTextFont -textvariable blocklist -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo44" "OptionBlock" vTcl:WidgetProc "TopLevel" 1
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Sector 
    vTcl:DefineAlias "$top.lab46" "Label1" vTcl:WidgetProc "TopLevel" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Block 
    vTcl:DefineAlias "$top.lab48" "Label2" vTcl:WidgetProc "TopLevel" 1
    checkbutton $top.speaker \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Disable Speaker Beep} -variable speaker 
    vTcl:DefineAlias "$top.speaker" "SpeakerDisable" vTcl:WidgetProc "TopLevel" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent46 \
        -in $top -x 40 -y 40 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 90 -y 10 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 70 -y 70 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 140 -y 70 -anchor nw -bordermode ignore 
    place $top.tCo43 \
        -in $top -x 30 -y 130 -width 83 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo44 \
        -in $top -x 135 -y 130 -width 83 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 50 -y 105 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 160 -y 105 -anchor nw -bordermode ignore 
    place $top.speaker \
        -in $top -x 55 -y 155 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

